name: AWS ECR Push
run-name: ${{ github.actor }} pushing ECR Image
on:
  push:
    branches: [main]
env:
  AWS_ECR_ROLE: ${{ vars.AWS_ECR_ROLE }}
  AWS_ECR_REGISTRY: ${{ vars.AWS_ECR_REGISTRY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
permissions:
  id-token: write
  contents: read
jobs:
  Push-Docker-Image-To-ECR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ECR_ROLE }}
          role-session-name: ECRPushSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ env.AWS_ECR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY:$IMAGE_TAG .
          docker push $REGISTRY:$IMAGE_TAG